name: Makefile CI (Testing)

on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3", "3.7", "3.8", "3.9", "3.10"]
    name: Build (Python ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v3
      - name: Use Cache for Python Dependencies
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Requirements 
        run: make requirements
      - name: Lint
        run: make lint
      - name: Build
        run: make build
